trigger:
  branches:
    include:
      - main  # Change this if you're working with another branch

pool:
  vmImage: 'windows-latest'  # Uses a Windows machine to match your Jenkins setup

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'  # Make sure the version matches your Python 3.11 setup
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest-html  # Ensure pytest-html is installed
    displayName: 'Install Python Dependencies'

  - script: |
      python -m playwright install
    displayName: 'Install Playwright Dependencies'

  - script: |
      python -m pytest --html=reportbdd.html
    displayName: 'Run Selenium BDD Tests'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'reportbdd.html'  # Publish the test report
      ArtifactName: 'TestReport'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'screenshots'
      artifactName: 'Screenshots'

  - task: Cache@2
    inputs:
      key: 'python | "$(Agent.OS)" | requirements.txt'
      restoreKeys: |
        python | "$(Agent.OS)"
      path: $(PIP_CACHE)
    continueOnError: true